### ISSUE TITLE
Bug: Conversion results for 'submit a form' goal is erroneous

### ISSUE THREAD

**Issue by PriyaBhatia0210** [humanmade/altis-analytics#111]
humanmade/product-dev#602

Currently, platform-test doesn't support any form submission hence, 'submit a form' goal in the editor should always render 0 conversions when selected. 

**Steps to reproduce:**
1. Create an XB and assign audience
2. Add a link and add a conversion goal as 'click on any link'
3. Update page and view the page on the frontend
4. Click on the link to verify conversion
5. Go back to the editor, it will correctly show the conversion goal as satisfied and the no. of times the link was clicked.
6. Now, if you select the conversion goal as 'submit a form', the conversion goal no. should turn 0. However, it continues to show the conversion no from the 'click on the link' results of the previous conversion goal.   

![Erroneous result for form submission](https://user-images.githubusercontent.com/55112796/104761488-f8d9c480-5730-11eb-865c-dd6a639e42d6.gif)

**Comment by roborourke** [comment]
Ok, chatted with Priya after digging into this a bit. There was an obvious issue when switching between impressions and either of the other 2 conversion goals which is addressed by https://github.com/humanmade/experiments/pull/65

The deeper issue however is that what does it mean for the data if someone changes a conversion goal from say clicks to form submissions. Right now we don't discern any difference between the type of conversion - they're all conversions belonging to that variant.

Should we track when the XB was last edited and only fetch data from that point on? That would keep the data meaningful by not mixing 2 different types of conversions and also by only revealing data related to the current published version of the XB. Technically even if just the XB content has been changed any existing data is invalid or at least less meaningful.

Perhaps the XB ID (stored currently as the `clientId` should be stored as a hash of its content and configuration rather than the UUID given to it by the block editor so that we only display data pertinent to that instance of it. This also means if the data is modified and then changed back to a previous value it should pick up the right info.

**Comment by rmccue** [comment]
Discussed this a bit with Rob, and I think the best solution here is to let the user decide.

Blocks could be edited for a small wording change (like a spelling mistake) which shouldn't affect data collection, or even a large change (eg Gutenberg's built-in buttons to a custom button block) but where the data is still semantically the same. On the flip side, you could have no actual change to a block but a conceptual change, like if a site went through a redesign even though the block's content doesn't change.

Rather than trying to guess the intent of the user, we can guide them and provide them with tools. Based on that, seems like there's two parts to resolving it:
* Caution the user that changing the content may make the data meaningless
* Provide a button to the user to allow them to reset data (i.e. regenerate ID)

This also provides more power to the user, and it's possible there's other use cases we haven't thought of where having a button could be useful to users (resetting before a new marketing campaign?). Providing power to the users allows them to decide, and we can always iterate to guide them further or pave any cowpaths in the future to improve usability.
